### ISSUE TITLE
Random_marks 

### ISSUE THREAD

**Issue by shaikmujahed** [PythonNut/hmcenterprise#1]
Function gives syntax error.
 def random_marks (3, 2, 3):
        random_marks (" '''65''' ", ''' "67" ''', ''' ""89"" ''')
Print (random_marks)

**Comment by taigrr** [comment]
I agree, that's invalid code, but what does this have to do with an empty repo?

**Comment by shaikmujahed** [comment]
@taigrr 
Give the output using integer  2,3,2 as parameters in a function that should return a string.

**Comment by taigrr** [comment]
@shaikmujahed I'm happy to help you figure out how to call a function in python and understand the rules you need to follow for it to work, but it's generally not acceptable to open an issue on a random stranger's repo on GitHub for help, especially when it has nothing to do with the question you're asking. That's what forums and chat groups are for. GitHub issues are for proposing changes to code and filing bug reports. There's no code in this repo so you're definitely not doing either of those. Perhaps you should try asking a question on StackOverflow or something.

Unfortunately, there are so many things wrong with the code snippet you posted that I don't know how to begin to help you. Hopefully you can do some more research on your own first and figure out what it is you're trying to accomplish. 

Best of luck!
